### PR TITLE
Create `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**

### CODE REVIEW

**Comment by mpustovoi** [comment]
I hope you will also consider removing the replacement of the Minecraft logo and edition. It's really too much.
https://github.com/z3n01d/man-from-the-fog-reimagined/issues/4#issuecomment-2241284350
The panorama is enough to indicate the presence of your mod. Although maybe it wouldn't hurt to make it optional.

**Comment by zenolth** [comment]
I'll remove the custom Minecraft logo, but it's really hard to just "add an option" to disable the panorama and you must understand that.

**Review by zenolth — APPROVED** [review]

**Comment by mpustovoi** [comment]
The built-in resource pack can be a solution.

**Comment by zenolth** [comment]
I don't think that mods can create resource packs, also, why do you have a problem with the panorama? Most people that I asked don't mind and actually think that it's cool, and the original did the same thing.

**Comment by mpustovoi** [comment]
I don't have a problem with a panorama. It's okay for the horror-themed modpack.
It was all about the logo. I think it shouldn't be more than a random splash.

**Comment by SpvceR3ii** [comment]
GUYS HES COMING THE MAN IS COMING THE MAN IS COMING HELP ME HELP ME HELP ME HELP ME

hi how are ya

**Comment by mpustovoi** [comment]
> I don't think that mods can create resource packs

I know that `Continuity`, `Presence Footsteps` (default sounds) and `Eating Animation` (mods support) have built-in resourcepacks.
Unfortunately, I don't know about the implementation, but that seems possible.

**Pull request merged**
